import type { LessonDefinition } from "./types";

export const lesson_3_2: LessonDefinition = {
  id: "3-2",
  title: "Otherwise Clause (Else and Elif)",
  questions: [
    {
      kind: "shortAnswer",
      id: "3-2-q1",
      prompt: "In coding, else is used to run a block of code only when the if condition is ___",
      placeholder: "Type your answer",
      acceptableAnswers: ["false", "False"],
      caseSensitive: false,
    },
    {
      kind: "tokenAssemble",
      id: "3-2-q2",
      prompt: "Duo wants to show \"Access Denied\" if the password is wrong. Assemble the logic!",
      contextLines: ["Tap tokens to fill boxes from left to right. Tap a filled box to remove it."],
      slotCount: 3,
      tokens: [":", "print(\"Access Denied\")", "else"],
      correctOrder: ["else", ":", "print(\"Access Denied\")"],
    },
    {
      kind: "singleChoice",
      id: "3-2-q3",
      prompt: "Look at the code. What does Duo say?",
      contextLines: [
        "1. is_raining = True",
        "2. if is_raining == False:",
        "3.     print(\"Go outside!\")",
        "4. else:",
        "5.     print(\"Stay inside!\")",
      ],
      options: ["Go outside!", "Stay inside!"],
      correctAnswer: "Stay inside!",
    },
    {
      kind: "singleChoice",
      id: "3-2-q4",
      prompt:
        "What keyword do we use if we want to check a second specific condition before giving up and going to the else?",
      options: ["maybe_if", "elif (or else if)", "if_again"],
      correctAnswer: "elif (or else if)",
    },
    {
      kind: "matchDrag",
      id: "3-2-q5",
      prompt: "Match the light color to the correct code block!",
      contextLines: ["Drag each action to the matching condition, then press Submit."],
      leftItems: ["if light == \"green\":", "elif light == \"yellow\":", "else:"],
      draggableValues: ["Drive", "Slow down", "Stop"],
      correctValues: ["Drive", "Slow down", "Stop"],
      appendEqualsToLeftItems: false,
    },
    {
      kind: "singleChoice",
      id: "3-2-q6",
      prompt: "What is the result if score = 85?",
      contextLines: [
        "1. if score > 90:",
        "2.     print(\"A\")",
        "3. elif score > 80:",
        "4.     print(\"B\")",
        "5. else:",
        "6.     print(\"C\")",
      ],
      options: ["A", "B", "C"],
      correctAnswer: "B",
    },
    {
      kind: "singleChoice",
      id: "3-2-q7",
      prompt: "In an if/else structure, can both blocks of code run at the same time?",
      options: [
        "Yes, if they are both true.",
        "No, only one path is ever chosen.",
        "Only on Tuesdays.",
      ],
      correctAnswer: "No, only one path is ever chosen.",
    },
    {
      kind: "singleChoice",
      id: "3-2-q8",
      prompt: "Duo tried to write this code, but the computer is confused. Why?",
      contextLines: ["1. else: print(\"You lose!\")"],
      options: [
        "You can't have an else without an if first.",
        "The word lose is a bug.",
        "It needs a semicolon.",
      ],
      correctAnswer: "You can't have an else without an if first.",
    },
    {
      kind: "tokenAssemble",
      id: "3-2-q9",
      prompt:
        "If temp = 30, the code skips if temp > 80 and elif temp > 60. Which block will it run?",
      slotCount: 1,
      tokens: ["if", "elif", "else"],
      correctOrder: ["else"],
    },
    {
      kind: "singleChoice",
      id: "3-2-q10",
      prompt: "What should Duo wear based on this code?",
      contextLines: [
        "1. is_sunny = False",
        "2. is_snowing = True",
        "3. if is_sunny:",
        "4.     wear(\"Sunglasses\")",
        "5. elif is_snowing:",
        "6.     wear(\"Boots\")",
        "7. else:",
        "8.     wear(\"Sneakers\")",
      ],
      options: ["Sunglasses", "Boots", "Sneakers"],
      correctAnswer: "Boots",
    },
  ],
};
