import type { LessonDefinition } from "./types";

export const lesson_3_3: LessonDefinition = {
  id: "3-3",
  title: "AND / OR Logic",
  questions: [
    {
      kind: "singleChoice",
      id: "3-3-q1",
      prompt: "When using and, how many conditions must be true for the whole statement to be true?",
      options: ["Only one.", "Both of them.", "None of them."],
      correctAnswer: "Both of them.",
    },
    {
      kind: "singleChoice",
      id: "3-3-q2",
      prompt: "When using or, how many conditions must be true for the whole statement to be true?",
      options: ["At least one.", "Both must be True.", "Both must be False."],
      correctAnswer: "At least one.",
    },
    {
      kind: "singleChoice",
      id: "3-3-q3",
      prompt: "Can Duo go to the park?",
      contextLines: [
        "1. is_sunny = True",
        "2. has_umbrella = False",
        "3. if is_sunny or has_umbrella:",
        "4.     print(\"Go to park\")",
      ],
      options: ["Yes", "No"],
      correctAnswer: "Yes",
      hintText: "Because it is sunny, the umbrella does not matter for an or condition.",
    },
    {
      kind: "tokenAssemble",
      id: "3-3-q4",
      prompt: "Duo can only level up if he has 100 coins and a trophy. Assemble the logic!",
      contextLines: ["Tap tokens to fill boxes from left to right. Tap a filled box to remove it."],
      slotCount: 9,
      slotRows: 2,
      tokens: [":", "==", "if", "has_trophy", "100", "and", "coins", "True", "=="],
      correctOrder: ["if", "coins", "==", "100", "and", "has_trophy", ":"],
      allowPartialFill: true,
      correctOrders: [
        ["if", "coins", "==", "100", "and", "has_trophy", ":"],
        ["if", "has_trophy", "and", "coins", "==", "100", ":"],
        ["if", "coins", "==", "100", "and", "has_trophy", "==", "True", ":"],
        ["if", "has_trophy", "==", "True", "and", "coins", "==", "100", ":"],
      ],
    },
    {
      kind: "multiSelect",
      id: "3-3-q5",
      prompt: "Which of these statements result in true?",
      contextLines: ["Select 2 choices, then press Submit."],
      options: [
        "(5 > 3) and (10 > 2)",
        "(1 > 10) and (5 == 5)",
        "(1 > 10) or (5 == 5)",
        "(2 == 3) or (4 == 0)",
      ],
      correctAnswers: ["(5 > 3) and (10 > 2)", "(1 > 10) or (5 == 5)"],
      requiredSelectionCount: 2,
      layoutColumns: 2,
    },
    {
      kind: "singleChoice",
      id: "3-3-q6",
      prompt: "Does the user get logged in?",
      contextLines: [
        "1. correct_user = True",
        "2. correct_pass = False",
        "3. if correct_user and correct_pass:",
        "4.     print(\"Welcome!\")",
      ],
      options: ["Yes", "No"],
      correctAnswer: "No",
      hintText: "Both conditions must be true to pass an and check.",
    },
    {
      kind: "tokenAssemble",
      id: "3-3-q7",
      prompt: "Duo wants coffee. He will go if he has cash ____ if he has a credit card.",
      slotCount: 1,
      tokens: ["and", "or", "=="],
      correctOrder: ["or"],
    },
    {
      kind: "singleChoice",
      id: "3-3-q8",
      prompt: "The keyword not flips a Boolean. What is the result of not False?",
      options: ["True", "False", "Maybe"],
      correctAnswer: "True",
    },
    {
      kind: "singleChoice",
      id: "3-3-q9",
      prompt: "Duo wants to let people in if they are 18 OR have a ticket. Why is this code buggy?",
      contextLines: ["1. if age >= 18 and has_ticket == True:", "2.     print(\"Enter\")"],
      options: [
        "It needs an else.",
        "It uses and (requiring both), but it should use or (requiring one).",
        "The number 18 is a string.",
      ],
      correctAnswer: "It uses and (requiring both), but it should use or (requiring one).",
    },
    {
      kind: "singleChoice",
      id: "3-3-q10",
      prompt: "What does the console print?",
      contextLines: [
        "1. health = 50",
        "2. has_shield = True",
        "3. is_boss_near = True",
        "4. if (health > 0 and is_boss_near) and has_shield:",
        "5.     print(\"Fight!\")",
        "6. else:",
        "7.     print(\"Run!\")",
      ],
      options: ["Fight!", "Run!"],
      correctAnswer: "Fight!",
    },
  ],
};
