import type { LessonDefinition } from "./types";

export const lesson_2_3: LessonDefinition = {
  id: "2-3",
  title: "True or False (Booleans)",
  questions: [
    {
      kind: "multiSelect",
      id: "2-3-q1",
      prompt: "A Boolean is a data type that can only have two possible values. What are they?",
      contextLines: ["Select 2 choices, then press Submit."],
      options: ["Yes", "1", "False", "No", "0", "True"],
      correctAnswers: ["False", "True"],
      requiredSelectionCount: 2,
      layoutColumns: 3,
    },
    {
      kind: "matchDrag",
      id: "2-3-q2",
      prompt: "Match the Boolean value to the real-world state!",
      contextLines: ["Drag each room state to the correct Boolean line, then press Submit."],
      leftItems: ["is_lamp_on = True", "is_lamp_on = False"],
      draggableValues: ["The room is bright.", "The room is dark."],
      correctValues: ["The room is bright.", "The room is dark."],
    },
    {
      kind: "singleChoice",
      id: "2-3-q3",
      prompt: "Which of these is a Boolean, not a String?",
      options: ["\"True\"", "True", "\"False\""],
      correctAnswer: "True",
      hintText: "Booleans do not wear coats (quotation marks).",
    },
    {
      kind: "multiSelect",
      id: "2-3-q4",
      prompt: "Duo is making a game. Which of these should be stored as Booleans?",
      contextLines: ["Select 2 choices, then press Submit."],
      options: ["is_game_over", "player_name", "has_gold_key", "coin_count"],
      correctAnswers: ["is_game_over", "has_gold_key"],
      requiredSelectionCount: 2,
    },
    {
      kind: "shortAnswer",
      id: "2-3-q5",
      prompt: "Can you help Duo mute his music?",
      contextLines: ["Type the value for is_muted."],
      inputPrefix: "is_muted =",
      placeholder: "Type True or False",
      acceptableAnswers: ["True"],
      caseSensitive: true,
      statusEmoji: "🔊",
      statusEmojiCrossOnCorrect: true,
    },
    {
      kind: "singleChoice",
      id: "2-3-q6",
      prompt: "Booleans often come from math questions. What is the result of 5 > 3?",
      options: ["True", "False"],
      correctAnswer: "True",
      explanationOnCorrect: "Because 5 is indeed greater than 3!",
    },
    {
      kind: "singleChoice",
      id: "2-3-q7",
      prompt: "To open the secret door, has_key must be ____.",
      options: ["True", "False", "100"],
      correctAnswer: "True",
    },
    {
      kind: "tokenAssemble",
      id: "2-3-q8",
      prompt: "Create a variable called is_sunny and set it to False.",
      contextLines: ["Tap tokens to fill boxes from left to right. Tap a filled box to remove it."],
      slotCount: 3,
      tokens: ["is_sunny", "False", "="],
      correctOrder: ["is_sunny", "=", "False"],
    },
    {
      kind: "singleChoice",
      id: "2-3-q9",
      prompt: "Which of these is NOT a Boolean?",
      options: ["True", "False", "Maybe"],
      correctAnswer: "Maybe",
    },
    {
      kind: "singleChoice",
      id: "2-3-q10",
      prompt: "Look at the variables. Is Duo's phone ringing?",
      contextLines: ["1. battery_level = 10", "2. is_calling = True", "3. is_silent_mode = False"],
      options: ["Yes (True)", "No (False)"],
      correctAnswer: "Yes (True)",
      explanationOnCorrect: "Because is_calling is True and it is not on silent mode.",
    },
  ],
};
